# image: https://hub.docker.com/r/bitnami/mediawiki

version: '3.8'

services:
  mediawiki:
    image: bitnami/mediawiki:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - ${APP_PORT}:8080
    environment:
      - MEDIAWIKI_DATABASE_HOST=mysql
      - MEDIAWIKI_DATABASE_USER=${DB_MYSQL_USER}
      - MEDIAWIKI_DATABASE_NAME=${DB_MYSQL_NAME}
      - MEDIAWIKI_DATABASE_PORT_NUMBER=${DB_MYSQL_PORT}
      - MEDIAWIKI_DATABASE_PASSWORD=${DB_MYSQL_PASSWORD}
      - MEDIAWIKI_USERNAME=${APP_USER}
      - MEDIAWIKI_PASSWORD=${APP_PASSWORD}
      - MEDIAWIKI_EMAIL=${APP_EMAIL}
      - MEDIAWIKI_WIKI_NAME=${APP_SITENAME}
      #- MEDIAWIKI_EXTERNAL_HTTP_PORT_NUMBER=${APP_PORT}
    volumes:
      - mediawiki:/bitnami/mediawiki
    links:
      - mysql
    restart: always

  mysql:
    image: mysql:${DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-mysql
    restart: always
    ports:
     - ${DB_MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}

networks:
  default:
      name: ${APP_NAME}

volumes:
  mediawiki:
  mysql: