# image: https://hub.docker.com/r/ubcctlt/mediawiki

version: '3.8'

services:
  mediawiki:
    image: ubcctlt/mediawiki:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - ${APP_PORT}:80
    environment:
      - MEDIAWIKI_DB_HOST=mysql
      - MEDIAWIKI_DB_USER=${DB_MYSQL_USER}
      - MEDIAWIKI_DB_NAME=${DB_MYSQL_NAME}
      - MEDIAWIKI_DB_PORT=${DB_MYSQL_PORT}
      - MEDIAWIKI_DB_PASSWORD=${DB_MYSQL_PASSWORD}
      - MEDIAWIKI_ADMIN_USER=${APP_USER}
      - MEDIAWIKI_ADMIN_PASS=${APP_PASSWORD}
      - MEDIAWIKI_SITE_LANG=${APP_LANGUANGE}
      - MEDIAWIKI_SITE_NAME=${APP_SITENAME}
      - MEDIAWIKI_SITE_SERVER="http://8.142.3.195"
      #- MEDIAWIKI_EXTENSIONS
    volumes:
      - mediawiki:/data
    links:
      - mysql
    restart: always

  mysql:
    image: mysql:${DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-mysql
    restart: always
    ports:
     - ${DB_MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}

networks:
  default:
      name: ${APP_NAME}

volumes:
  mediawiki:
  mysql: